MvcStok/MvcStok/Controllers/ÜrünController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MvcStok.Models.Entity;


namespace MvcStok.Controllers
{
    public class ÜrünController : Controller
    {
        // GET: Ürün
        MvcDBStokEntities db = new MvcDBStokEntities();
        public ActionResult Index()
        {
            var degerler = db.TBLURUNLER.ToList();
            return View(degerler);
        }
        [HttpGet]
        public ActionResult UrunEkle()
        {
            List<SelectListItem> degerler = (from i in db.TBLKATEGORILER.ToList()
                                             select new SelectListItem
                                             {
                                                 Text = i.KATEGORIAD,
                                                 Value = i.KATEGORIID.ToString()
                                             }).ToList();
            ViewBag.dgr = degerler;
            return View();
        }
        [HttpPost]
        public ActionResult UrunEkle(TBLURUNLER p1)
        {
            var ktg = db.TBLKATEGORILER.Where(m=> m.KATEGORIID == p1.TBLKATEGORILER.KATEGORIID).FirstOrDefault();
            p1.TBLKATEGORILER = ktg;
            db.TBLURUNLER.Add(p1);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult SIL(int id)
        {
            var urun = db.TBLURUNLER.Find(id);
            db.TBLURUNLER.Remove(urun);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult UrunGetir(int id)
        {

            var urun = db.TBLURUNLER.Find(id);

            List<SelectListItem> degerler = (from i in db.TBLKATEGORILER.ToList()
                                             select new SelectListItem
                                             {
                                                 Text = i.KATEGORIAD,
                                                 Value = i.KATEGORIID.ToString()
                                             }).ToList();
            ViewBag.dgr = degerler;

            return View("UrunGetir", urun);
        }
        public ActionResult Guncelle(TBLURUNLER p)
        {
            var urun = db.TBLURUNLER.Find(p.URUNID);
            urun.URUNADI = p.URUNADI;
            urun.MARKA = p.MARKA;
            urun.STOK = p.STOK;
            urun.FIYAT = p.FIYAT;
            //urun.URUNKATEGORI = p.URUNKATEGORI;
            var ktg = db.TBLKATEGORILER.Where(m => m.KATEGORIID == p.TBLKATEGORILER.KATEGORIID).FirstOrDefault();
            urun.URUNKATEGORI = ktg.KATEGORIID;
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        
    }
}

MvcStok/MvcStok/Views/Ürün/Index.cshtml
@using MvcStok.Models.Entity;
@model List<TBLURUNLER>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}

<table id="tbl1" class="table table-bordered">
    <thead>
        <tr>
            <th>ÜRÜN ID</th>
            <th>ÜRÜN ADI</th>
            <th>MARKASI</th>
            <th>KATEGORİ</th>
            <th>FİYAT</th>
            <th>STOK</th>
            <th>SİL</th>
            <th>GÜNCELLE</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var urn in Model)
        {
            <tr>
                <th>@urn.URUNID</th>
                <td>@urn.URUNADI</td>
                <td>@urn.MARKA</td>
                @*<td>@urn.TBLKATEGORILER.KATEGORIAD</td>*@
                <td>@urn.FIYAT</td>
                <td>@urn.STOK</td>
                <td><a href="/Ürün/SIL/@urn.URUNID" class="btn btn-danger">SİL</a></td>
                <td><a href="/Ürün/UrunGetir/@urn.URUNID" class="btn btn-success">GÜNCELLE</a></td>
            </tr>
        }
    </tbody>
</table>
<a href="/Ürün/UrunEkle/" class="btn btn-primary">YENİ ÜRÜN EKLE</a>

MvcStok/MvcStok/Views/Ürün/UrunEkle.cshtml
@model MvcStok.Models.Entity.TBLURUNLER
@{
    ViewBag.Title = "UrunEkle";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}

namespace MvcStok.Controllers
{
    public class ÜrünController : Controller
    {
        // GET: Ürün
        MvcDBStokEntities db = new MvcDBStokEntities();
        public ActionResult Index()
        {
            var degerler = db.TBLURUNLER.ToList();
            return View(degerler);
        }
        [HttpGet]
        public ActionResult UrunEkle()
        {
            List<SelectListItem>
    degerler = (from i in db.TBLKATEGORILER.ToList()
    select new SelectListItem
    {
    Text = i.KATEGORIAD,
    Value = i.KATEGORIID.ToString()
    }).ToList();
    ViewBag.dgr = degerler;
    return View();
    }
    [HttpPost]
    public ActionResult UrunEkle(TBLURUNLER p1)
    {
    var ktg = db.TBLKATEGORILER.Where(m=> m.KATEGORIID == p1.TBLKATEGORILER.KATEGORIID).FirstOrDefault();
    p1.TBLKATEGORILER = ktg;
    db.TBLURUNLER.Add(p1);
    db.SaveChanges();
    return RedirectToAction("Index");
    }
    public ActionResult SIL(int id)
    {
    var urun = db.TBLURUNLER.Find(id);
    db.TBLURUNLER.Remove(urun);
    db.SaveChanges();
    return RedirectToAction("Index");
    }
    public ActionResult UrunGetir(int id)
    {

    var urun = db.TBLURUNLER.Find(id);

    List<SelectListItem>
        degerler = (from i in db.TBLKATEGORILER.ToList()
        select new SelectListItem
        {
        Text = i.KATEGORIAD,
        Value = i.KATEGORIID.ToString()
        }).ToList();
        ViewBag.dgr = degerler;

        return View("UrunGetir", urun);
        }
        public ActionResult Guncelle(TBLURUNLER p)
        {
        var urun = db.TBLURUNLER.Find(p.URUNID);
        urun.URUNADI = p.URUNADI;
        urun.MARKA = p.MARKA;
        urun.STOK = p.STOK;
        urun.FIYAT = p.FIYAT;
        //urun.URUNKATEGORI = p.URUNKATEGORI;
        var ktg = db.TBLKATEGORILER.Where(m => m.KATEGORIID == p.TBLKATEGORILER.KATEGORIID).FirstOrDefault();
        urun.URUNKATEGORI = ktg.KATEGORIID;
        db.SaveChanges();
        return RedirectToAction("Index");
        }

        }
        }

MvcStok/MvcStok/Views/Ürün/UrunGetir.cshtml
@model MvcStok.Models.Entity.TBLURUNLER
@{
    ViewBag.Title = "UrunGetir";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}

@using (Html.BeginForm("Guncelle", "Ürün", FormMethod.Post))
{
<div class="form-group">
    @Html.LabelFor(m => m.URUNID)
    @Html.TextBoxFor(m => m.URUNID, new { @class = "form-control" })
    <br />
    @Html.LabelFor(m => m.URUNADI)
    @Html.TextBoxFor(m => m.URUNADI, new { @class = "form-control" })
    <br />
    @Html.LabelFor(m => m.MARKA)
    @Html.TextBoxFor(m => m.MARKA, new { @class = "form-control" })
    <br />
    @Html.LabelFor(m => m.URUNKATEGORI)
    @Html.DropDownListFor(m=>m.TBLKATEGORILER.KATEGORIID,(List<SelectListItem>)ViewBag.dgr, new { @class = "form-control" })
    @*@Html.TextBoxFor(m => m.URUNKATEGORI, new { @class = "form-control" })*@

    <br />
    @Html.LabelFor(m => m.FIYAT)
    @Html.TextBoxFor(m => m.FIYAT, new { @class = "form-control" })
    <br />
    @Html.LabelFor(m => m.STOK)
    @Html.TextBoxFor(m => m.STOK, new { @class = "form-control" })
</div>
    <div>
        <button class="btn btn-warning">Ürün Güncelle</button>
    </div>
}